### ISSUE TITLE
error - trying to compile EFIperun 

### ISSUE THREAD

**Issue by toddfraser88** [jethrogb/uefireverse#6]
I get this error trying to compile efiperun -

$ make
objcopy --redefine-sym mmap=wrapped_mmap jemalloc-3.6.0/lib/libjemalloc_pic.a jemalloc_custom.a
cp jemalloc-3.6.0/include/jemalloc/jemalloc.h jemalloc_custom.h
g++ -I/usr/local/include/efi -I/usr/local/include/efi/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c stubs.cpp -o stubs.o
In file included from /usr/local/include/efi/efi.h:50:0,
                 from main.h:23,
                 from stubs.cpp:33:
/usr/local/include/efi/efipxebc.h:422:16: error: using typedef-name ‘EFI_PXE_BASE_CODE_PROTOCOL’ after ‘struct’
 typedef struct EFI_PXE_BASE_CODE_PROTOCOL EFI_PXE_BASE_CODE;
                ^
/usr/local/include/efi/efipxebc.h:414:3: note: ‘EFI_PXE_BASE_CODE_PROTOCOL’ has a previous declaration here
 } EFI_PXE_BASE_CODE_PROTOCOL;
   ^
Makefile:25: recipe for target 'stubs.o' failed
make: *** [stubs.o] Error 1
$

any help?

**Comment by jethrogb** [comment]
I think you are using gnu-efi version 3.0.5, which is broken. Use 3.0.4 or older, or 3.0.6 or newer.

Bug introduced in https://sourceforge.net/p/gnu-efi/code/ci/751cbce3f640c79fbb4660cb59a372b79a7f4d11/tree/inc/efipxebc.h
Fixed in https://sourceforge.net/p/gnu-efi/code/ci/bf07e8141777e5a2d67ec8447084215224bdad4b/tree/inc/efipxebc.h

**Comment by jethrogb** [comment]
Closing due to lack of feedback
